## About this app

This software was developed for the IRAMAT-CRP2A, Université Bordeaux Montaigne (France)
to analyse Al<sub>2</sub>O<sub>3</sub>:C chip measurements. The analysis assumed that the measurements
were solely carried out as described in Kreutzer et al. (2018). For all calculations functions from the R package 'Luminescence' are used. 

**Version**: 0.1.2 [2018-06-14]

**Author**: Sebastian Kreutzer, IRAMAT-CRP2A, UMR 5060, CNRS - Université Bordeaux Montaigne (France)

**Contact**: sebastian.kreutzer@u-bordeaux-montaigne.fr
  
## References to cite

Kreutzer, S., Burow, C., Dietze, M., Fuchs, Margret C., Schmidt, C., Fischer, M., Friedrich, J. ```r strtrim(Sys.Date(), 4)```. Luminescence: Comprehensive Luminescence Dating Data Analysis. R package version ```r packageDescription("Luminescence")$Version```. [https://CRAN.R-project.org/package=Luminescence](https://CRAN.R-project.org/package=Luminescence)

Kreutzer S., Martin L., Guérin G., Tribolo C., Selva P., Mercier N., 2018.
Environmental Dose Rate Determination Using a Passive Dosimeter: Techniques and Workflow for alpha-Al2O3:C Chips.Geochronometria 45, 56-67. doi: [10.1515/geochr-2015-0086](http://dx.doi.org/10.1515/geochr-2015-0086)

Kreutzer, S., Schmidt, C., Fuchs, M.C., Dietze, M., Fischer, M., Fuchs, M., 2012. 
Introducing an R package for luminescence dating analysis. Ancient TL 30 (1), 1–8.

## Licence

This program is free software: you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by the
Free Software Foundation, either version 3 of the License, or any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU [General Public License](https://www.gnu.org/licenses/gpl-3.0.en.html) for more details
