## News and changes

### Version 0.1.13 (2022-10-20)
* Add additional column in Post-processing pane to allow a correction of the 
the source dose rate. This might come in handy of different chips thickness need 
an adjustment of the dose rate
* A few minor fixes, silencing terminal warnings (no user visible changes)

### Version 0.1.12 (2022-04-13)
#### Bugfixes and changes
* Fixes a potential problem with the file import due to a missing argument.
* Add hash-code for a sequence without TL curves.

### Version 0.1.11 (2021-04-17)
#### Bugfixes and changes
* Fix a problem that prevented the app running with a updated version of 'shiny'

### Version 0.1.10 (2019-04-18)
#### Bugfixes and changes
* The signal integral was not used correctly, resulting in results different from what would 
be calculated using the R function alone
* Panel 'Post-processing': the plot output is now more meaningful and allows bivariate plots if
more then one column is selected
* Panel 'Settings': housekeeping and minor error correction

### Version 0.1.9 (2019-04-08)
#### Bugfixes and changes
* Panel 'Post-processing': Column 'FINAL GAMMA_DR.ERROR [µGy/a]' was not correctly calculated; corrected.

### Version 0.1.8 (2019-04-05)
#### Bugfixes and changes
* Panel 'Post-processing': Column 'CV %' was not correct
* Panel 'Post-processing': Column 'FINAL GAMMA_DR.ERROR [%]' could be negative, corrected

#### User visible changes
* Panel 'Post-processing' the data aggregation runs automatically if the panel is selected, 
i.e. the button 'Aggregate data' was removed.

### Version 0.1.7 (2019-01-16)

#### Bugfixes and changes
* Colour ramp removed in table in panel 'Analyse'
* Colour sorting in 'Post-processing' now deactivated to avoid confusions 


### Version 0.1.6 (2019-01-15)

#### New features
* Support table sorting in the panel 'Analyse' without screwing up the plots
* Add additional columns in the panel 'Post-processing'
* The table in the panel 'Post-processing' is now active and plots whatever is provided

#### Bugfixes
* The dose value in the plots in the subtext in the panel 
'Analyse' was not shown correctly; fixed. '
* The cosmic dose was not subtracted correclty; fixed.


### Version 0.1.5 (2018-12-20)

* Add current and calibration dose rate disply in tab 'Analyse'

### Version 0.1.4 (2018-09-20)
* If the position numbering did not start with position 1, this was not displayed correctly on the carousel plot and the travel dosimeter correction did not work; fixed.
* The sample names in the boxplot are now displayed with a 45˚ angle to avoid overplotting.
* The auto-generated sample ids used the position numbers, but without a leading 0. This caused some re-ordering of the samples in the last panel; fixed. 

### Version 0.1.3
* Add option to allow the wheel number assignment based on the file name and not the position number. 
This in particular helpful if you want to mix different files for one analysis. 
* The context menu 'Download to CSV' was not working in the panel 'post-processing' due to an 
error in the underlying JavaScript code; the workaround presets the columns with 0, which circumvents this 
error. 
* Add columns for measurement date, attenuation factor, cosmic dose and corrected dose including 
the calculation logic in panel 'Post-processing'. 


### Version 0.1.2
* Add Panel 'Settings' with session information and an option to download the calibration data
* Panel 'Settings': Now supports uploading an own calibration dataset
* Internals: The app now verifies the data structure of the imported files based on a reference 
has. If the has values do not match the dataset is automatically excluded. 


### Version 0.1.1

* Panel 'Analyse': Add option for multiple calibrations datasets
* Panel 'Analyse': The plots shown for a selected row are no correct even if the datasets was resorted or the panel was switched; however for this the column 
sorting was disabled until the underlying widget supports the option to be needed to enable this feature again
* Panel 'Post-processing': Add source dose rate values and units to final output table

### Version 0.1.0

* Initial version 
